import { HighlightStyle } from '@codemirror/language';
import { tags } from '@lezer/highlight';
import { EditorView } from '@codemirror/view';

export function buildMarkdownEditorTheme(dark: boolean, fontFamily: string, fontSize: number) {
  return EditorView.theme(
    {
      '&': {
        height: '100%',
        fontSize: `${fontSize}px`,
        fontFamily,
        backgroundColor: 'var(--background)',
      },
      '.cm-scroller': { overflowX: 'hidden', overflowY: 'auto', lineHeight: '1.7', fontFamily },
      '.cm-content': {
        padding: '16px max(16px, min(48px, calc(50% - 430px)))',
        caretColor: 'var(--primary)',
      },
      '&.cm-focused .cm-selectionBackground': {
        background: 'var(--editor-selection)',
        borderRadius: '3px',
      },
      '.cm-selectionBackground': {
        background: 'var(--editor-selection-dim)',
        borderRadius: '3px',
      },
      '.cm-selectionBackground + .cm-selectionBackground': {
        borderTopLeftRadius: '0',
        borderTopRightRadius: '0',
      },
      '&.cm-focused .cm-selectionBackground + .cm-selectionBackground': {
        borderTopLeftRadius: '0',
        borderTopRightRadius: '0',
      },
      '.cm-selectionBackground:has(+ .cm-selectionBackground)': {
        borderBottomLeftRadius: '0',
        borderBottomRightRadius: '0',
      },
      '&.cm-focused .cm-selectionBackground:has(+ .cm-selectionBackground)': {
        borderBottomLeftRadius: '0',
        borderBottomRightRadius: '0',
      },
      '.cm-selectionMatch': {
        background: 'var(--editor-selection-dim)',
        outline: '1px solid var(--editor-selection)',
        borderRadius: '3px',
      },
      '&.cm-focused .cm-cursor': {
        borderLeftColor: 'var(--primary)',
        borderLeftWidth: '2px',
      },
      '.cm-gutters': {
        backgroundColor: 'var(--background)',
        border: 'none',
        color: 'var(--muted-foreground)',
        paddingLeft: 'max(0px, min(24px, calc(50% - 454px)))',
      },
      '.cm-lineNumbers .cm-gutterElement': {
        padding: '0 8px 0 4px',
        minWidth: '2.5em',
        textAlign: 'right',
        fontFamily: "ui-monospace, 'SFMono-Regular', 'Cascadia Mono', 'Cascadia Code', 'JetBrains Mono', Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
      },
      '.cm-indent-marker': {
        color: 'var(--muted-foreground)',
        opacity: '0.45',
        pointerEvents: 'none',
        display: 'inline-block',
        whiteSpace: 'pre',
      },
      '.cm-indent-marker-space': {
        textAlign: 'center',
      },
      '.cm-indent-marker-tab': {
        textAlign: 'left',
      },
      '.cm-indent-guide-depth-0': { boxShadow: 'inset 2px 0 0 oklch(from var(--primary) l c h / 0.38)', backgroundColor: 'oklch(from var(--primary) l c h / 0.06)' },
      '.cm-indent-guide-depth-1': { boxShadow: 'inset 2px 0 0 oklch(0.82 0.17 210 / 0.42)', backgroundColor: 'oklch(0.82 0.17 210 / 0.06)' },
      '.cm-indent-guide-depth-2': { boxShadow: 'inset 2px 0 0 oklch(0.86 0.15 160 / 0.42)', backgroundColor: 'oklch(0.86 0.15 160 / 0.06)' },
      '.cm-indent-guide-depth-3': { boxShadow: 'inset 2px 0 0 oklch(0.83 0.19 40 / 0.42)', backgroundColor: 'oklch(0.83 0.19 40 / 0.06)' },
      '.cm-indent-guide-depth-4': { boxShadow: 'inset 2px 0 0 oklch(0.80 0.20 320 / 0.42)', backgroundColor: 'oklch(0.80 0.20 320 / 0.06)' },
      '.cm-indent-guide-depth-5': { boxShadow: 'inset 2px 0 0 oklch(0.88 0.12 80 / 0.42)', backgroundColor: 'oklch(0.88 0.12 80 / 0.06)' },
      '.cm-ascii-arrow-ligature': {
        display: 'inline-block',
        width: '2ch',
        textAlign: 'center',
        pointerEvents: 'none',
      },
      '.cm-color-preview-swatch': {
        appearance: 'none',
        display: 'inline-block',
        width: '0.8em',
        height: '0.8em',
        borderRadius: '3px',
        border: '1px solid transparent',
        marginRight: '0.35em',
        verticalAlign: '-0.08em',
        boxShadow: '0 0 0 1px oklch(1 0 0 / 0.08), 0 1px 2px oklch(0 0 0 / 0.24)',
        cursor: 'copy',
        padding: '0',
      },
      '.cm-color-preview-swatch:hover': {
        transform: 'translateY(-0.5px)',
        boxShadow: '0 0 0 1px oklch(1 0 0 / 0.12), 0 3px 10px oklch(0 0 0 / 0.24)',
      },
      '.cm-color-preview-swatch:focus-visible': {
        outline: '2px solid var(--primary)',
        outlineOffset: '2px',
      },
      '.cm-color-preview-token': {
        border: '1px solid transparent',
        borderRadius: '4px',
        padding: '0 0.22em',
        boxDecorationBreak: 'clone',
        WebkitBoxDecorationBreak: 'clone',
      },
      '.cm-activeLine': {
        backgroundColor: 'oklch(from var(--foreground) l c h / 4%)',
        fontVariantLigatures: 'none',
        fontFeatureSettings: '"liga" 0, "calt" 0',
      },
      '.cm-activeLineGutter': { backgroundColor: 'transparent' },
      '.cm-strong': { fontWeight: 'bold' },
      '.cm-em': { fontStyle: 'italic' },
      '.cm-link': { color: 'var(--primary)', textDecoration: 'underline' },
      '.cm-url': { color: 'color-mix(in oklch, var(--primary) 70%, var(--muted-foreground))' },
      '.cm-code': { fontFamily: 'monospace' },
      '.cm-strikethrough': { textDecoration: 'line-through' },
      '.cm-tooltip': {
        border: '1px solid color-mix(in oklch, var(--border) 60%, transparent)',
        borderRadius: '8px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.35)',
        overflow: 'hidden',
        backgroundColor: 'color-mix(in oklch, var(--popover) 92%, transparent)',
      },
      '.cm-tooltip-autocomplete': {
        fontFamily: "'Geist Variable', system-ui, sans-serif",
      },
      '.cm-tooltip-autocomplete ul': {
        margin: '0',
        padding: '4px',
        minWidth: '220px',
        maxWidth: '340px',
        maxHeight: '260px',
      },
      '.cm-tooltip-autocomplete ul li': {
        display: 'flex',
        alignItems: 'center',
        padding: '5px 8px',
        borderRadius: '5px',
        cursor: 'pointer',
        lineHeight: '1.4',
        gap: '8px',
      },
      '.cm-tooltip-autocomplete ul li[aria-selected]': {
        background: 'color-mix(in oklch, var(--primary) 15%, transparent)',
        color: 'var(--foreground)',
      },
      '.cm-completionLabel': {
        fontSize: '13px',
        color: 'var(--foreground)',
        flex: '1',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      },
      '.cm-completionDetail': {
        fontSize: '11px',
        color: 'var(--muted-foreground)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        maxWidth: '120px',
        textAlign: 'right',
        fontStyle: 'normal',
      },
      '.cm-completionIcon': {
        display: 'none',
      },
    },
    { dark },
  );
}

export function buildMarkdownHighlightStyle(dark: boolean) {
  const p = dark ? {
    keyword: '#c678dd',
    control: '#e06c75',
    string: '#98c379',
    number: '#d19a66',
    bool: '#d19a66',
    nil: '#d19a66',
    type: '#e5c07b',
    fn: '#61afef',
    prop: '#abb2bf',
    variable: '#abb2bf',
    definition: '#e06c75',
    operator: '#56b6c2',
    punctuation: '#abb2bf',
    comment: '#5c6370',
    meta: '#5c6370',
    tag: '#e06c75',
    attr: '#d19a66',
    attrVal: '#98c379',
    invalid: '#f44747',
    heading: '#e5c07b',
    link: '#61afef',
    url: '#56b6c2',
    code: '#abb2bf',
  } : {
    keyword: '#a626a4',
    control: '#a626a4',
    string: '#50a14f',
    number: '#986801',
    bool: '#986801',
    nil: '#986801',
    type: '#c18401',
    fn: '#4078f2',
    prop: '#383a42',
    variable: '#383a42',
    definition: '#e45649',
    operator: '#0184bc',
    punctuation: '#383a42',
    comment: '#a0a1a7',
    meta: '#a0a1a7',
    tag: '#e45649',
    attr: '#986801',
    attrVal: '#50a14f',
    invalid: '#ca1243',
    heading: '#c18401',
    link: '#4078f2',
    url: '#0184bc',
    code: '#383a42',
  };

  return HighlightStyle.define([
    { tag: tags.comment, color: p.comment, fontStyle: 'italic' },
    { tag: tags.lineComment, color: p.comment, fontStyle: 'italic' },
    { tag: tags.blockComment, color: p.comment, fontStyle: 'italic' },
    { tag: tags.docComment, color: p.comment, fontStyle: 'italic' },
    { tag: tags.keyword, color: p.keyword },
    { tag: tags.modifier, color: p.keyword },
    { tag: tags.controlKeyword, color: p.control },
    { tag: tags.operatorKeyword, color: p.control },
    { tag: tags.definitionKeyword, color: p.keyword },
    { tag: tags.moduleKeyword, color: p.control },
    { tag: tags.self, color: p.keyword },
    { tag: tags.namespace, color: p.type },
    { tag: tags.string, color: p.string },
    { tag: tags.special(tags.string), color: p.string },
    { tag: tags.regexp, color: p.string },
    { tag: tags.escape, color: p.number },
    { tag: tags.number, color: p.number },
    { tag: tags.integer, color: p.number },
    { tag: tags.float, color: p.number },
    { tag: tags.bool, color: p.bool, fontWeight: 'bold' },
    { tag: tags.null, color: p.nil, fontWeight: 'bold' },
    { tag: tags.typeName, color: p.type },
    { tag: tags.typeOperator, color: p.type },
    { tag: tags.className, color: p.type },
    { tag: tags.definition(tags.typeName), color: p.type, fontWeight: 'bold' },
    { tag: tags.variableName, color: p.variable },
    { tag: tags.definition(tags.variableName), color: p.definition },
    { tag: tags.function(tags.variableName), color: p.fn },
    { tag: tags.function(tags.propertyName), color: p.fn },
    { tag: tags.propertyName, color: p.prop },
    { tag: tags.definition(tags.propertyName), color: p.definition },
    { tag: tags.function(tags.name), color: p.fn },
    { tag: tags.labelName, color: p.variable },
    { tag: tags.operator, color: p.operator },
    { tag: tags.arithmeticOperator, color: p.operator },
    { tag: tags.logicOperator, color: p.operator },
    { tag: tags.bitwiseOperator, color: p.operator },
    { tag: tags.compareOperator, color: p.operator },
    { tag: tags.updateOperator, color: p.operator },
    { tag: tags.definitionOperator, color: p.operator },
    { tag: tags.punctuation, color: p.punctuation },
    { tag: tags.separator, color: p.punctuation },
    { tag: tags.bracket, color: p.punctuation },
    { tag: tags.squareBracket, color: p.punctuation },
    { tag: tags.paren, color: p.punctuation },
    { tag: tags.brace, color: p.punctuation },
    { tag: tags.derefOperator, color: p.operator },
    { tag: tags.tagName, color: p.tag },
    { tag: tags.attributeName, color: p.attr },
    { tag: tags.attributeValue, color: p.attrVal },
    { tag: tags.angleBracket, color: p.punctuation },
    { tag: tags.documentMeta, color: p.meta },
    { tag: tags.processingInstruction, color: p.meta },
    { tag: tags.meta, color: p.meta },
    { tag: tags.atom, color: p.bool },
    { tag: tags.unit, color: p.number },
    { tag: tags.constant(tags.name), color: p.number },
    { tag: tags.color, color: p.number },
    { tag: tags.invalid, color: p.invalid, textDecoration: 'underline wavy' },
    { tag: tags.heading, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading1, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading2, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading3, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading4, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading5, color: p.heading, fontWeight: 'bold' },
    { tag: tags.heading6, color: p.heading, fontWeight: 'bold' },
    { tag: tags.link, color: p.link },
    { tag: tags.url, color: p.url },
    { tag: tags.emphasis, fontStyle: 'italic' },
    { tag: tags.strong, fontWeight: 'bold' },
    { tag: tags.strikethrough, textDecoration: 'line-through' },
    { tag: tags.monospace, fontFamily: 'monospace', color: p.code },
    { tag: tags.content, color: dark ? '#abb2bf' : '#383a42' },
  ]);
}
